version: '3'

services:
    java11:
        image: openjdk:11-bullseye
        command: /bin/sh -c "while sleep 1000; do :; done"
        volumes:
            - ..:/workspace:cached
            - gradle-cache:/workspace/.gradle

    postgres13:
        image: postgres:13
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
        volumes:
            - ./initdb:/docker-entrypoint-initdb.d

volumes:
    gradle-cache:
